%%{init: {'theme': 'dark', 'themeVariables': { 'primaryTextColor': 'white'}}}%%
graph LR
    B[pandas] --> A[data-science]
    C[matplotlib] --> A
    D[jupyter notebook] --> A
    E[geopandas] --> F[spatial-data-science]
    B --> F
    C --> F
    A --> X[Project A]
    A --> Y[Project B]
    F --> Z[Project C]